### ISSUE TITLE
NoMethodError: undefined method `<' for false:FalseClass

### ISSUE THREAD

**Issue by heaven** [richhollis/swagger-docs#133]
```
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:140:in `process_path'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:75:in `block in generate_doc'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:74:in `each'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:74:in `generate_doc'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:56:in `block in generate_docs'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:53:in `each'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:53:in `generate_docs'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/swagger/docs/generator.rb:24:in `write_docs'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/gems/swagger-docs-0.2.6/lib/tasks/swagger.rake:5:in `block (2 levels) in <top (required)>'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/bin/ruby_executable_hooks:15:in `eval'
/Users/heaven/.rvm/gems/ruby-2.2.1@clarion/bin/ruby_executable_hooks:15:in `<main>'
```

There's a typo in the code, at the line https://github.com/richhollis/swagger-docs/blob/master/lib/swagger/docs/generator.rb#L139

This:
```ruby
if config[:parent_controller] && !klass < config[:parent_controller]
```
Should probably be:
```ruby
if config[:parent_controller] && !(klass < config[:parent_controller])
```

**Comment by richhollis** [comment]
Ah yes - good spot. This came in on a recent PR and there wasn't any coverage for it. Thanks for the solution. This has been added with a basic spec to cover it.
