### ISSUE TITLE
Docs not getting generated for rails 5.0.0

### ISSUE THREAD

**Issue by ram619prasad** [richhollis/swagger-docs#140]
`rake swagger:docs
rake aborted!
NoMethodError: undefined method `source' for "GET":String
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:147:in `get_route_path_apis'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:128:in `block in process_path'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:127:in `each'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:127:in `process_path'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:62:in `block in generate_doc'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:61:in `each'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:61:in `generate_doc'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:49:in `block in generate_docs'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:46:in `each'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:46:in `generate_docs'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/swagger/docs/generator.rb:20:in `write_docs'
/home/ram/.rvm/gems/ruby-2.3.0/gems/swagger-docs-0.1.8/lib/tasks/swagger.rake:5:in `block (2 levels) in <top (required)>'
/home/ram/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => swagger:docs
(See full trace by running task with --trace)
`

I have routes something like this.
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
  	namespace :v1 do
  		resources :users
  	end
  end
end

I generated controller using 
rails g controller api/v1/users 

Please help me I'm stuck

**Comment by saiqulhaq** [comment]
I am getting this issue also :(

**Comment by ADO** [comment]
+1

**Comment by tomorrownull** [comment]
try this branch
gem 'swagger-docs',github: 'anhtrantuan/swagger-docs'

Support rails5 and fixed this problem

**Comment by papilip** [comment]
Many thanks, fix this pb for me ;-)
